### ISSUE TITLE
api definitions should not use absolute URIs 

### ISSUE THREAD

**Issue by kgignatyev-inspur** [vaibhav-sinha/kong-java-client#1]
When annotations start with / it causes Retrofit to ignore base URL and whole system does not work
@GET("/apis/")
    Call<ApiList> listApis(....

which prevents communicating with Kong behind some sort of proxy, in my case I have Kong working inside Kubernetes cluster, so my base proxied URL is 
http://localhost:8001/api/v1/namespaces/inspurusa/services/listless-liger-kong-admin:kong-admin/proxy/

I just made quick test and when I removed leading slash, then requests started to respect base URL
@GET("apis/")

Suggestion: remove all leading slashes from api definitions pretty much as retrofit hints http://square.github.io/retrofit/#introduction

**Comment by vaibhav-sinha** [comment]
Thanks for reporting this and the PR.

**Comment by kgignatyev-inspur** [comment]
You are welcome. 


Konstantin Ignatyev

Senior Technical Architect 
konstantin@inspur.com
