### ISSUE TITLE
Are recent releases published?

### ISSUE THREAD

**Issue by scottcarey** [vaibhav-sinha/kong-java-client#7]
Maven central has 0.1.0, however, it appears as though 0.1.3 might exist.

Are these published somewhere?

In particular, I need  `OAuth2ManageService#deleteConsumerApplication` which does not exist in 0.1.0

**Comment by vaibhav-sinha** [comment]
Version 0.2.0 is now released.

**Comment by javapowered** [comment]
@vaibhav-sinha for 0.2.0 do you know compatible kong version? (like 0.14.1 or 0.15.0 etc.)?

Thanks!

**Comment by javapowered** [comment]
@vaibhav-sinha may be you also know why ServiceService and RouteService from 0.1.4-rr are not included into 0.2.0 and what should be used instead?
